#!/bin/sh

set -e

SCRIPTFILE=`readlink -f $0`
SCRIPTROOT=`dirname $SCRIPTFILE`
ROOT=$(readlink -f ${SCRIPTROOT}/..)

BUILDROOT=$ROOT/build
BENCHROOT=$ROOT/benchmarks
RESULTROOT=$ROOT/results
HSENVROOT=$BUILDROOT/hsenvs
LOGDIR=$BUILDROOT/logs

SURVEYTOOLS_DIR=$SCRIPTROOT
BENCHRESULTS_DIR=$RESULTROOT/benchmark-summaries
BENCH_DIR=$SURVEYTOOLS_DIR/../benchmarks

setup() {
  $SURVEYTOOLS_DIR/setup/install-hsenv --nikola --accelerate-github --vanilla 7.4.2 vanilla --vanilla 7.6.1 vanilla
  $SURVEYTOOLS_DIR/benchmarkrunner/rebuildBenchmarkRunner.sh
}

benchmark() {

  LOGTAG=$(date +%Y-%m-%d-%H-%M-%S)
  cd $SURVEYTOOLS_DIR/benchmarkrunner
  for experiment in $BENCHROOT/*
  do
    if [ ! -d $experiment ]; then
      continue
    fi
    for platform in $experiment/*
    do
      if [ ! -d $platform ]; then
        continue
      fi
      $SURVEYTOOLS_DIR/benchmarkrunner/run.sh $(basename $experiment) $(basename $platform) $LOGTAG
    done
  done
  #runhaskell Main.hs Nikola Repa CUDA R Vector Accelerate
}

plot() {
  cd $SURVEYTOOLS_DIR/plotting

  LATEST=$(ls -c $BENCHRESULTS_DIR |head -n 1)

  Rscript ggplot_speedup.r --args $BENCHRESULTS_DIR/$LATEST binomial-cpu-Vector.csv
}

clean () {

  rm -rf $BUILDROOT/hsenvs
  rm -rf $BENCH_DIR/*/*/dist*

  # special cases, should really be handled locally.
  (
    cd $BENCH_DIR/binomial-gpu/CUDA/src-cpp
    make clean || true
    )
  (
    cd $BENCH_DIR/binomial-cpu/C
    make clean || true
    )

}

revdeps () {
  echo "Nothing here yet"

}

show_usage() {
  echo "Collects and plots all survey data"
  echo ""
  echo "Invoke with one or more of the following flags:"
  echo "  --clean         Clean up the various build files"
  echo "  --setup         Setup necessary GHC installations and build benchmarks"
  echo "  --benchmark     Runs benchmarks and generates graphs"
  echo "  --plot          Plot the lastest benchmark execution"
  echo "  --revdeps       Count reverse dependencies"
  echo "  --thebigbutton  Alias for '--setup --benchmark --plot'"
  echo "  --nightly       Alias for '-- clean --setup --benchmark --plot'"
  echo "  --usage"
}

if [ $# -lt 1 ]; then
    echo "No arguments given. Aborting."
    echo ""
    show_usage
    exit 1
fi


while [ $# -gt 0 ]; do
  case $1 in
    --clean)
      clean
      shift
      ;;
    --nightly)
      (
      clean
      setup
      benchmark
      plot
      ) > $BUILDROOT//logs/$(date +%Y-%m-%d,%H:%M:%S)-nightly-output
      shift
      ;;
    --setup)
      setup
      shift
      ;;
    --benchmark)
      benchmark
      shift
      ;;
    --revdeps)
      revdeps
      shift
      ;;
    --thebigbutton)
      setup
      benchmark
      plot
      shift
      ;;
    --plot)
      plot
      shift
      ;;
    --usage)
      show_usage
      break
      ;;
    *)
      echo "Unknown parameter $1"
      show_usage
      break
      ;;
  esac
done
