#!/bin/sh

set -e

SURVEYTOOLS_DIR=$(dirname $(readlink -f $0))
BUILD_DIR=$SURVEYTOOLS_DIR/../build
BENCHRESULTS_DIR=$SURVEYTOOLS_DIR/../results/benchmark-summaries
BENCH_DIR=$SURVEYTOOLS_DIR/../benchmarks

setup() {
  # Really, each benchmark should be responsible for its own setup (maybe aided by sourcing a library)
  $SURVEYTOOLS_DIR/setup/install-hsenv --nikola --accelerate-github --vanilla 7.4.2 vanilla
  cd $SURVEYTOOLS_DIR/benchmarkrunner
  runhaskell Main.hs -r
}

benchmark() {
  cd $SURVEYTOOLS_DIR/benchmarkrunner
  #runhaskell Main.hs all
  runhaskell Main.hs Repa CUDA R Vector
}

plot() {

  LATEST=$(ls -c $BENCHRESULTS_DIR |head -n 1)

  Rscript plotting/ggplot_speedup.r --args $BENCHRESULTS_DIR/$LATEST binomial-cpu-Vector.csv
}

clean () {

  rm -rf $BUILD_DIR/hsenvs
  rm -rf $BENCH_DIR/*/*/dist*

  # special cases, should really be handled locally.
  (
    cd $BENCH_DIR/binomial-gpu/CUDA/src-cpp
    make clean || true
    )
  (
    cd $BENCH_DIR/binomial-cpu/C
    make clean || true
    )

}

revdeps () {
  echo "Nothing here yet"

}

show_usage() {
  echo "Collects and plots all survey data"
  echo ""
  echo "Invoke with one or more of the following flags:"
  echo "  --clean         Clean up the various build files"
  echo "  --setup         Setup necessary GHC installations and build benchmarks"
  echo "  --benchmark     Runs benchmarks and generates graphs"
  echo "  --plot          Plot the lastest benchmark execution"
  echo "  --revdeps       Count reverse dependencies"
  echo "  --thebigbutton  Alias for '--setup --benchmark --plot'"
  echo "  --nightly       Alias for '-- clean --setup --benchmark --plot'"
  echo "  --usage"
}

if [ $# -lt 1 ]; then
    echo "No arguments given. Aborting."
    echo ""
    show_usage
    exit 1
fi


while [ $# -gt 0 ]; do
  case $1 in
    --clean)
      clean
      shift
      ;;
    --nightly)
      clean
      setup
      benchmark
      plot
      shift
      ;;
    --setup)
      setup
      shift
      ;;
    --benchmark)
      benchmark
      shift
      ;;
    --revdeps)
      revdeps
      shift
      ;;
    --thebigbutton)
      setup
      benchmark
      plot
      shift
      ;;
    --plot)
      plot
      shift
      ;;
    --usage)
      show_usage
      break
      ;;
    *)
      echo "Unknown parameter $1"
      show_usage
      break
      ;;
  esac
done
